Repository kerberos89/Devops-Teste, pull requests merged in 2018-10, with the labels that each got.

#14 Integrar arquitetura v1.0
  7 – Quais são os tipos de teste?.md
  8 – O que são testes do tipo Caixa Branca e Caixa Preta?.md
Labels: Arquitetura

#17 V1.0 programacao
  7 – Quais são os tipos de teste?.md
  8 – O que são testes do tipo Caixa Branca e Caixa Preta?.md
  TestCase.txt
  TextSuite.txt
Labels: Programação

#15 Adicionando resposta 9
  9-piramide-testes.md
Labels: Teste

#18 Adicionando resposta 9
  9-piramide-testes.md
Labels: Teste

#23 V1.0 programacao
  7 – Quais são os tipos de teste?.md
  8 – O que são testes do tipo Caixa Branca e Caixa Preta?.md
  TestCase.txt
  TextSuite.txt
Labels: Programação

#34 V1.0 arquitetura
  7 – Quais são os tipos de teste?
  8 – O que são testes do tipo Caixa Branca e Caixa Preta?
Labels: Arquitetura
